# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      env: TOXENV=py37
    - python: 3.6
      env: TOXENV=py36
    - python: 3.5
      env: TOXENV=py35
    - python: 2.7
      env: TOXENV=py27
    - python: 3.7
      dist: xenial
      env: TOXENV=flake8
    - python: 3.7
      dist: xenial
      env: TOXENV=docs
  allow_failures:
    - env: TOXENV=flake8
	  - env: TOXENV=docs

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libportaudio2 portaudio19-dev libasound2 libasound2-dev

# command to install dependencies, e.g. pip install -r requirements.txt
# --use-mirrors
install: pip install --upgrade tox coveralls

# command to run tests, e.g. python setup.py test
script: 
  tox -e ${TOXENV}

after_success:
  coveralls
