language: c
compiler: gcc


before_script:
        - sudo apt-get update -qq
        - sudo apt-get install libportaudio2
        - ./autogen.sh

script:
        - ./configure && make

# Whitelists
branches:
        only:
                - master
                - develop
